const PHASES = [
    { num: 1, label: "Exploration / Validation", color: "#30d158", subtitle: "3-5 documents  --  Poser les fondations du projet" },
    { num: 2, label: "Lancement structure", color: "#0a84ff", subtitle: "6-10 documents  --  Structurer et officialiser le projet" },
    { num: 3, label: "Croissance / Complexite", color: "#ff9f0a", subtitle: "12-18 documents  --  Gerer la montee en charge" },
    { num: 4, label: "Scale / Enterprise", color: "#ff453a", subtitle: "18-25+ documents  --  Operations a grande echelle" }
];

const AGENTS = [
    // === ETAPE 1 ===
    {
        id: 1, firstName: "Gabriel", lastName: "Morel",
        agentName: "Strategic Vision Architect", document: "Vision Document",
        phase: 1, color: "#30d158",
        photo: "assets/images/Gabriel Morel.webp",
        gptLink: "https://chatgpt.com/g/g-699f028df91881918adf4c18a0d5b067-gabriel-morel",
        shortDesc: "Definit pourquoi le projet existe et quelle ambition long terme il poursuit.",
        folder: "Agents/ÉTAPE 1 — Exploration - Validation/Vision Document",
        howToUse: "Lancez une conversation avec Gabriel en cliquant sur le bouton vert. Il va vous guider a travers un entretien structure en 6 phases : d'abord le cadrage de votre projet, puis l'exploration du \"Why\" (pourquoi ce projet existe), la definition de votre vision ambitieuse, l'identification de votre public cible, les principes directeurs, et enfin la synthese finale en document .md. Repondez a chaque question avec le plus de details possible. Si votre reponse est vague, il vous challengera.",
        whatFor: "Le Vision Document est la fondation de tout votre projet. C'est le PREMIER document a produire. Il definit l'ambition a 3-5 ans, le \"pourquoi\" fondamental du projet, et sert de boussole pour toutes les decisions strategiques futures. Sans ce document, votre equipe n'a pas de cap commun.",
        whyUse: "Parce qu'un projet sans vision claire est un navire sans gouvernail. Gabriel combine l'experience d'un Chief Product Officer et d'un Chief Strategy Officer. Il vous challengera comme un sparring partner strategique : il ne remplit pas le document a votre place, il vous aide a decouvrir et articuler VOTRE propre vision.",
        methodology: [
            { title: "Accueil et cadrage", desc: "Comprendre le contexte du projet", time: "1-2 echanges" },
            { title: "Exploration du \"Why\"", desc: "Creuser le pourquoi fondamental", time: "2-3 echanges" },
            { title: "Definition de la vision", desc: "Articuler l'ambition a long terme", time: "2-3 echanges" },
            { title: "Public cible et proposition de valeur", desc: "Identifier les utilisateurs et la valeur unique", time: "2-3 echanges" },
            { title: "Principes directeurs et criteres de succes", desc: "Definir les regles et mesures de reussite", time: "2-3 echanges" },
            { title: "Synthese et production", desc: "Generer le document final en .md", time: "1-2 echanges" }
        ]
    },
    {
        id: 2, firstName: "Esteban", lastName: "Durand",
        agentName: "Problem Detective", document: "Problem Statement",
        phase: 1, color: "#30d158",
        photo: "assets/images/Esteban Durand.webp",
        gptLink: "https://chatgpt.com/g/g-699f037d2ac48191b864616e0fafca18-esteban-durand",
        shortDesc: "Clarifie precisement le probleme reel que le projet cherche a resoudre.",
        folder: "Agents/ÉTAPE 1 — Exploration - Validation/Problem Statement",
        howToUse: "Lancez la conversation avec Esteban et decrivez votre projet. Attention : si vous commencez par parler de votre SOLUTION, il vous arretera poliment pour vous recentrer sur le PROBLEME. Il mene l'enquete methodiquement en 7 phases : identification du probleme reel (vs les symptomes), comprehension des personnes affectees, mesure de l'impact, collecte de preuves, et definition du resultat attendu.",
        whatFor: "Le Problem Statement est le deuxieme document de l'Etape 1. Il repond a la question fondamentale : quel probleme REEL resolvent-vous ? Il distingue les symptomes des causes racines. Un probleme mal defini mene inevitablement a une mauvaise solution.",
        whyUse: "42% des startups echouent parce qu'elles resolvent un probleme qui n'existe pas (CB Insights). Esteban possede la rigueur analytique d'un chercheur MIT, l'empathie d'un designer IDEO et la discipline d'un consultant McKinsey. Il est sceptique par nature et ne prend jamais un probleme pour argent comptant.",
        methodology: [
            { title: "Accueil et cadrage", desc: "Comprendre le contexte initial", time: "1-2 echanges" },
            { title: "Identification du probleme reel", desc: "Distinguer symptomes et causes racines", time: "3-4 echanges" },
            { title: "Comprendre les personnes affectees", desc: "Identifier qui souffre et comment", time: "2-3 echanges" },
            { title: "Mesurer l'impact", desc: "Quantifier le probleme en chiffres", time: "2-3 echanges" },
            { title: "Collecte de preuves", desc: "Rassembler donnees et observations", time: "1-2 echanges" },
            { title: "Definition du resultat attendu", desc: "Que se passe-t-il si le probleme est resolu ?", time: "1-2 echanges" },
            { title: "Synthese et production", desc: "Generer le document final en .md", time: "1-2 echanges" }
        ]
    },
    {
        id: 3, firstName: "Theo", lastName: "Lefevre",
        agentName: "Business Strategist", document: "Business Case",
        phase: 1, color: "#30d158",
        photo: "assets/images/Theo Lefevre.webp",
        gptLink: "https://chatgpt.com/g/g-699f03fafe2881918974f1401ebf3f69-theo-lefevre",
        shortDesc: "Explique pourquoi le projet peut etre viable economiquement ou strategiquement.",
        folder: "Agents/ÉTAPE 1 — Exploration - Validation/Business Case",
        howToUse: "Lancez la conversation avec Theo et presentez votre projet. Il va evaluer votre viabilite economique comme un investisseur bienveillant qui analyse un pitch. Il explore en 7 phases : l'opportunite de marche (TAM/SAM/SOM), votre modele economique, l'estimation des couts, l'analyse concurrentielle, les risques, et produit une recommandation Go/No-Go/Pivot.",
        whatFor: "Le Business Case est le troisieme document de l'Etape 1. Il repond a la question : ce projet peut-il etre viable economiquement ? Meme une vision brillante et un vrai probleme ne suffisent pas sans modele economique solide.",
        whyUse: "29% des startups echouent par manque de cash (CB Insights). Theo combine la rigueur d'un analyste Goldman Sachs, la vision d'un partner McKinsey et l'esprit d'un fondateur Y Combinator. Il exige des chiffres : \"Le marche est grand\" n'est PAS acceptable, \"Le SAM est estime a 500M EUR\" l'est.",
        methodology: [
            { title: "Accueil et cadrage", desc: "Comprendre le contexte du projet", time: "1-2 echanges" },
            { title: "Opportunite de marche", desc: "Analyser TAM, SAM, SOM", time: "2-3 echanges" },
            { title: "Modele economique", desc: "Definir comment gagner de l'argent", time: "3-4 echanges" },
            { title: "Estimation des couts", desc: "Calculer le burn rate et les investissements", time: "2-3 echanges" },
            { title: "Analyse concurrentielle", desc: "Identifier et analyser les concurrents", time: "2-3 echanges" },
            { title: "Risques et recommandation", desc: "Evaluer les risques et donner un verdict Go/No-Go", time: "2-3 echanges" },
            { title: "Synthese et production", desc: "Generer le Business Case final", time: "1-2 echanges" }
        ]
    },
    {
        id: 4, firstName: "Nathan", lastName: "Müller",
        agentName: "MVP Strategist & Scope Master", document: "Objectifs initiaux",
        phase: 1, color: "#30d158",
        photo: "assets/images/Nathan Müller.webp",
        gptLink: "https://chatgpt.com/g/g-699f048654fc8191af2a4e183d647194-nathan-muller",
        shortDesc: "Determine ce que doit accomplir la premiere version pour etre consideree comme reussie.",
        folder: "Agents/ÉTAPE 1 — Exploration - Validation/Objectifs initiaux",
        howToUse: "Lancez la conversation avec Nathan et expliquez votre projet. Il agit comme un gardien du scope : sa mission est de vous empecher de vouloir tout faire dans la v1. Il vous guide en 7 phases pour definir l'objectif principal, les objectifs secondaires, le perimetre MVP, les criteres de succes mesurables et les contraintes. Attention : si votre scope est trop gros, il REFUSERA de produire le document.",
        whatFor: "Les Objectifs initiaux sont le dernier document de l'Etape 1. C'est le pont entre la reflexion strategique et l'execution concrete (Etape 2). Il definit LE minimum qui prouve que le projet a de la valeur et transforme les idees vagues en objectifs SMART mesurables.",
        whyUse: "Sans objectifs clairs, le scope explose et le projet ne se termine jamais. Nathan combine la discipline de priorisation d'un PM Spotify, la methode d'un directeur Google et l'esprit Lean Startup. Son mantra : \"Moins mais mieux.\" Si tout est prioritaire, rien ne l'est.",
        methodology: [
            { title: "Accueil et cadrage", desc: "Comprendre le contexte du projet", time: "1-2 echanges" },
            { title: "Objectif principal", desc: "Definir LE but principal du MVP", time: "2-3 echanges" },
            { title: "Objectifs secondaires", desc: "Identifier les objectifs complementaires", time: "1-2 echanges" },
            { title: "Perimetre MVP", desc: "Delimiter ce qui est IN et OUT", time: "3-4 echanges" },
            { title: "Criteres de succes", desc: "Definir comment mesurer la reussite", time: "2-3 echanges" },
            { title: "Contraintes et hypotheses", desc: "Identifier les limites et suppositions", time: "2-3 echanges" },
            { title: "Synthese et production", desc: "Generer le document final", time: "1-2 echanges" }
        ]
    },
    // === ETAPE 2 ===
    { id: 5, firstName: "Lea", lastName: "Marchand", agentName: "CharterBot", document: "Project Charter", phase: 2, color: "#0a84ff", photo: "assets/images/Lea Marchand.webp", gptLink: "https://chatgpt.com/g/g-699f0506cd548191866d697574db3efe-lea-marchand", shortDesc: "Officialise le projet en definissant son cadre, son scope, ses responsabilites et ses objectifs.", folder: "Agents/ÉTAPE 2 — Lancement structuré/Project Charter", howToUse: "Lancez la conversation avec Lea et decrivez votre projet. Elle procede par phases structurees : decouverte, approfondissement, challenge, structuration, puis redaction. Elle ne genere JAMAIS le document final sans avoir pose TOUTES les questions necessaires.", whatFor: "Le Project Charter est le document fondateur de votre projet. Il officialise son existence, definit son cadre, son perimetre, ses responsabilites et ses objectifs. Il protege l'equipe contre le scope creep.", whyUse: "Sans charter, le projet n'a pas de mandat officiel. Les roles sont flous, le scope change constamment. Lea a plus de 15 ans d'experience chez Google, Amazon, Netflix et Spotify.", methodology: [ { title: "Decouverte", desc: "Comprendre le projet et son contexte", time: "5-10 min" }, { title: "Approfondissement", desc: "Explorer chaque dimension en detail", time: "15-20 min" }, { title: "Challenge", desc: "Identifier les incoherences et faiblesses", time: "10-15 min" }, { title: "Structuration", desc: "Organiser les informations", time: "5-10 min" }, { title: "Redaction", desc: "Produire le document final", time: "5 min" } ] },
    { id: 6, firstName: "Mathieu", lastName: "Colin", agentName: "PRDBot", document: "PRD", phase: 2, color: "#0a84ff", photo: "assets/images/Mathieu Colin.webp", gptLink: "https://chatgpt.com/g/g-699f059888b08191a6a3427bb9ef6dd0-mathieu-colin", shortDesc: "Detaille exactement ce que le produit doit contenir et comment il doit fonctionner.", folder: "Agents/ÉTAPE 2 — Lancement structuré/PRD", howToUse: "Lancez la conversation avec Mathieu et decrivez votre produit. Il utilise les frameworks RICE, ICE et Kano pour prioriser les fonctionnalites. Il distingue ce que l'utilisateur DEMANDE de ce dont il a BESOIN.", whatFor: "Le PRD detaille chaque fonctionnalite, chaque user story, chaque critere d'acceptation. Sans PRD, chaque developpeur interprete les besoins a sa maniere.", whyUse: "Mathieu est obsede par la clarte : une user story mal formulee le fait physiquement mal. Il verifie que chaque feature repond a un besoin documente. Experience chez Google, Amazon, Spotify et Stripe.", methodology: [ { title: "Decouverte produit", desc: "Comprendre le produit et son contexte", time: "10-15 min" }, { title: "Exploration des utilisateurs", desc: "Comprendre les personas et parcours", time: "10-15 min" }, { title: "Definition des fonctionnalites", desc: "Lister et detailler chaque feature", time: "15-20 min" }, { title: "Challenge produit", desc: "Questionner et prioriser", time: "10-15 min" }, { title: "Structuration et redaction", desc: "Produire le PRD final", time: "10 min" } ] },
    { id: 7, firstName: "Sarah", lastName: "Klein", agentName: "RoadmapBot", document: "Roadmap", phase: 2, color: "#0a84ff", photo: "assets/images/Sarah Klein.webp", gptLink: "https://chatgpt.com/g/g-699f0631212c81918c32b5234f805b6d-sarah-klein", shortDesc: "Organise les grandes phases de developpement dans le temps.", folder: "Agents/ÉTAPE 2 — Lancement structuré/Roadmap", howToUse: "Lancez la conversation avec Sarah. Elle vous guidera pour creer une roadmap outcome-driven. Elle deteste les roadmaps avec des dates precises pour chaque fonctionnalite : \"Une roadmap n'est pas un diagramme de Gantt.\"", whatFor: "La Roadmap organise les grandes phases, definit les jalons cles et communique la direction a toutes les parties prenantes.", whyUse: "Sarah pense en outcomes, pas en outputs. Elle distingue engagement et aspiration et integre des points de decision. Experience chez Spotify, Google et Basecamp.", methodology: [ { title: "Vision et strategie", desc: "Clarifier le cap et les objectifs", time: "10-15 min" }, { title: "Themes et initiatives", desc: "Identifier les grands chantiers", time: "15-20 min" }, { title: "Priorisation et sequencement", desc: "Ordonner par impact et faisabilite", time: "10-15 min" }, { title: "Challenge et stress-test", desc: "Tester la robustesse du plan", time: "10-15 min" }, { title: "Structuration et redaction", desc: "Produire la roadmap finale", time: "10 min" } ] },
    { id: 8, firstName: "Gaetan", lastName: "Simon", agentName: "TechSpecBot", document: "Technical Specification", phase: 2, color: "#0a84ff", photo: "assets/images/Gaetan Simon.webp", gptLink: "https://chatgpt.com/g/g-699f06b7f4608191ae3e1f3aaddeee5f-gaetan-simon", shortDesc: "Decrit l'architecture technique et les choix d'implementation.", folder: "Agents/ÉTAPE 2 — Lancement structuré/Technical Specification", howToUse: "Lancez la conversation avec Gaetan. Il exige que chaque choix technique soit justifie avec des avantages, inconvenients et alternatives. Il pense toujours a la scalabilite, la maintenabilite et la securite.", whatFor: "La Tech Spec decrit l'architecture du systeme et les choix technologiques. Sans ce document, chaque developpeur fait des choix techniques locaux sans vision globale.", whyUse: "Un choix technique sans justification rend Gaetan nerveux. Il insiste sur les trade-offs. Experience chez Google, Stripe, Netflix et Amazon.", methodology: [ { title: "Comprehension du contexte", desc: "Comprendre le business et les contraintes", time: "10 min" }, { title: "Exploration de l'architecture", desc: "Definir les composants et flux", time: "15-20 min" }, { title: "Exigences transverses", desc: "Securite, performance, maintenabilite", time: "10-15 min" }, { title: "Challenge technique", desc: "Questionner chaque choix", time: "15-20 min" }, { title: "Structuration et redaction", desc: "Produire la spec technique", time: "10 min" } ] },
    { id: 9, firstName: "Karim", lastName: "Haddad", agentName: "DecisionBot", document: "Decision Log", phase: 2, color: "#0a84ff", photo: "assets/images/Karim Haddad.webp", gptLink: "https://chatgpt.com/g/g-699f076f95508191b84edd0b19d6a128-karim-haddad", shortDesc: "Archive les decisions importantes prises et les raisons derriere ces choix.", folder: "Agents/ÉTAPE 2 — Lancement structuré/Decision Log", howToUse: "Lancez la conversation avec Karim et parlez-lui des decisions prises dans votre projet. Il anticipe les questions que quelqu'un posera dans 6 mois en relisant le log.", whatFor: "Le Decision Log est la memoire de votre projet. Sans ce document, les decisions sont re-debattues constamment et les nouveaux membres ne comprennent pas le \"pourquoi\" des choix.", whyUse: "Pour Karim, une decision non documentee est une decision qui n'existe pas. Fervent defenseur du \"disagree and commit\" d'Amazon. Experience chez Amazon, Atlassian, Netflix et Google.", methodology: [ { title: "Inventaire des decisions", desc: "Identifier les decisions a documenter", time: "10-15 min" }, { title: "Approfondissement", desc: "Explorer contexte, alternatives, consequences", time: "20-30 min" }, { title: "Challenge", desc: "Verifier la coherence globale", time: "10-15 min" }, { title: "Classification et structuration", desc: "Organiser par categorie et priorite", time: "5-10 min" }, { title: "Redaction", desc: "Produire le Decision Log final", time: "10 min" } ] },
    { id: 10, firstName: "Fanny", lastName: "Robert", agentName: "MetricsBot", document: "OKRs / Metrics Document", phase: 2, color: "#0a84ff", photo: "assets/images/Fanny Robert.webp", gptLink: "https://chatgpt.com/g/g-699f08046144819195e20be1855ea72a-fanny-robert", shortDesc: "Definit les objectifs mesurables permettant d'evaluer la performance du projet.", folder: "Agents/ÉTAPE 2 — Lancement structuré/OKRs Metrics Document", howToUse: "Lancez la conversation avec Fanny. Elle commence par la North Star Metric, puis definit les Objectives, les Key Results mesurables avec baselines et cibles. Elle verifie que vos OKR ne sont pas des taches deguisees.", whatFor: "Le document OKRs / Metrics definit comment mesurer si votre projet reussit ou echoue. Sans metriques, vous naviguez a l'aveugle.", whyUse: "Fanny challenge les metriques de vanite : \"Le nombre de pages vues a augmente de 30%. Et alors ?\" Elle distingue metriques input des metriques output. Experience OKR chez Google, Spotify et Amazon.", methodology: [ { title: "North Star et vision", desc: "Definir LA metrique ultime de succes", time: "10 min" }, { title: "Definition des Objectives", desc: "Formuler les objectifs qualitatifs", time: "10-15 min" }, { title: "Definition des Key Results", desc: "Creer des resultats mesurables", time: "15-20 min" }, { title: "Challenge", desc: "Tester la robustesse des OKR", time: "10-15 min" }, { title: "Tableau de bord et cadence", desc: "Definir le suivi et les revues", time: "10 min" }, { title: "Structuration et redaction", desc: "Produire le document final", time: "10 min" } ] },
    // === ETAPE 3 ===
    { id: 11, firstName: "Adrien", lastName: "Roche", agentName: "Lead UX Researcher", document: "UX Research Document", phase: 3, color: "#ff9f0a", photo: "assets/images/Adrien Roche.webp", gptLink: "https://chatgpt.com/g/g-699f08837a3c8191b0ec622c56e2133b-adrien-roche", shortDesc: "Documente les recherches utilisateurs et les insights qui guident l'experience produit.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/UX Research Document", howToUse: "Lancez la conversation avec Adrien. Il est allergique au biais de confirmation et le debusque systematiquement. Si une hypothese est faible, il vous le dira clairement.", whatFor: "Le UX Research Document capture les enseignements de la recherche utilisateur. C'est la source de verite pour comprendre les vrais problemes des utilisateurs.", whyUse: "Adrien a plus de 15 ans d'experience chez Google, Spotify, Airbnb et Amazon. Il garantit que vos decisions produit sont basees sur des preuves, pas des suppositions.", methodology: [ { title: "Contexte", desc: "Comprendre le produit et ses enjeux", time: "5-8 min" }, { title: "Objectifs de recherche", desc: "Definir ce qu'on cherche a apprendre", time: "5-8 min" }, { title: "Methodologie", desc: "Choisir les methodes de recherche", time: "5-8 min" }, { title: "Participants", desc: "Definir le panel de recherche", time: "3-5 min" }, { title: "Resultats", desc: "Analyser et synthetiser les insights", time: "10-15 min" }, { title: "Revue et finalisation", desc: "Produire le document final", time: "5 min" } ] },
    { id: 12, firstName: "Pauline", lastName: "Richard", agentName: "Staff API Architect", document: "API Specification", phase: 3, color: "#ff9f0a", photo: "assets/images/Pauline Richard.webp", gptLink: "https://chatgpt.com/g/g-699f0e2488ec81918b7d905c8edb8e16-pauline-richard", shortDesc: "Definit precisement comment les systemes et services communiquent entre eux.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/API Specification", howToUse: "Lancez la conversation avec Pauline. Elle pense toujours aux edge cases et scenarios d'erreur AVANT les cas nominaux. Un endpoint mal nomme la fait physiquement mal.", whatFor: "L'API Specification est le contrat qui definit comment vos systemes communiquent. Elle impacte directement l'experience developpeur (DX) et la maintenabilite.", whyUse: "Pauline a concu des APIs pour des millions de developpeurs chez Stripe, Google, Twilio et Zalando. Perfectionniste mais pragmatique.", methodology: [ { title: "Contexte systeme", desc: "Comprendre l'architecture globale", time: "5-8 min" }, { title: "Ressources et modele", desc: "Definir les entites et relations", time: "8-10 min" }, { title: "Design des endpoints", desc: "Concevoir chaque endpoint", time: "10-15 min" }, { title: "Securite et authentification", desc: "Definir les mecanismes d'acces", time: "5-8 min" }, { title: "Operabilite et evolution", desc: "Versioning, deprecation, monitoring", time: "5-8 min" }, { title: "Revue et finalisation", desc: "Produire la spec API finale", time: "5 min" } ] },
    { id: 13, firstName: "Julien", lastName: "Perrin", agentName: "Principal Data Architect", document: "Data Specification", phase: 3, color: "#ff9f0a", photo: "assets/images/Julien Perrin.webp", gptLink: "https://chatgpt.com/g/g-699f0f6cb15481918ea04e51ffcdc1ca-julien-perrin", shortDesc: "Structure les modeles de donnees et leur organisation logique.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/Data Specification", howToUse: "Lancez la conversation avec Julien et decrivez votre domaine metier. Il fait la distinction nette entre modele logique et physique. Vigilant sur les questions RGPD.", whatFor: "La Data Specification est le plan directeur de l'organisation de vos donnees. C'est la reference commune entre les equipes dev, data et compliance.", whyUse: "Julien a concu des modeles de donnees supportant des milliards de transactions chez Amazon, Spotify, Netflix et Airbnb. Il pense toujours a l'evolution.", methodology: [ { title: "Domaine metier", desc: "Comprendre le domaine et les bounded contexts", time: "8-10 min" }, { title: "Entites et bounded contexts", desc: "Identifier les entites principales", time: "8-10 min" }, { title: "Attributs et relations", desc: "Detailler chaque entite et ses liens", time: "10-15 min" }, { title: "Strategie technique", desc: "Indexation, partitioning, caching", time: "5-8 min" }, { title: "Conformite et gouvernance", desc: "RGPD, classification, retention", time: "5-8 min" }, { title: "Migration et evolution", desc: "Planifier l'evolution du schema", time: "5 min" } ] },
    { id: 14, firstName: "Yassine", lastName: "El Amrani", agentName: "Principal Security Engineer", document: "Security Review Document", phase: 3, color: "#ff9f0a", photo: "assets/images/Yassine El Amrani.webp", gptLink: "https://chatgpt.com/g/g-699f0ff85e308191bc71342ecc962988-yassin-el-amrani", shortDesc: "Analyse les risques de securite et les mesures de protection a mettre en place.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/Security Review Document", howToUse: "Lancez la conversation avec Yassine. \"On verra plus tard\" est sa phrase ennemie numero un. Il pense comme un attaquant pour mieux defendre.", whatFor: "Le Security Review Document analyse la posture de securite de votre systeme : actifs a proteger, menaces, mesures de protection, procedures de reponse aux incidents.", whyUse: "Yassine pratique le \"assume breach\" en permanence. Pragmatique : la securite parfaite n'existe pas, mais le risk management intelligent oui. Experience chez Google, Netflix, Microsoft et Stripe.", methodology: [ { title: "Cartographier le systeme", desc: "Identifier tous les composants et flux", time: "8-10 min" }, { title: "Classifier les donnees", desc: "Evaluer la sensibilite de chaque type", time: "5-8 min" }, { title: "Modeliser les menaces", desc: "Appliquer STRIDE/OWASP", time: "10-15 min" }, { title: "Evaluer les controles", desc: "Analyser les defenses existantes", time: "5-8 min" }, { title: "Definir les recommandations", desc: "Prioriser les actions de securite", time: "8-10 min" }, { title: "Conformite et validation", desc: "Verifier les standards applicables", time: "5 min" } ] },
    { id: 15, firstName: "Thomas", lastName: "Laurent", agentName: "Staff SRE", document: "Performance Plan", phase: 3, color: "#ff9f0a", photo: "assets/images/Thomas Laurent.webp", gptLink: "https://chatgpt.com/g/g-699f10811bc881919296d998f69fd574-thomas-laurent", shortDesc: "Definit comment le produit doit gerer la charge, la scalabilite et l'optimisation.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/Performance Plan", howToUse: "Lancez la conversation avec Thomas. Pas de \"ca devrait aller\" : il veut des benchmarks, des P99 et des SLOs.", whatFor: "Le Performance Plan anticipe les defis de charge et planifie la scalabilite avec des objectifs mesurables.", whyUse: "Thomas est obsede par les chiffres. Il distingue toujours latence, throughput et capacite. Il a gere des systemes servant des milliards de requetes chez Google, Netflix, Amazon et Cloudflare.", methodology: [ { title: "Systeme et enjeux", desc: "Comprendre l'architecture et les risques", time: "5-8 min" }, { title: "Objectifs de performance", desc: "Definir SLOs, SLIs, SLAs", time: "8-10 min" }, { title: "Capacite actuelle", desc: "Identifier les goulots d'etranglement", time: "8-10 min" }, { title: "Projections de charge", desc: "Anticiper la croissance", time: "5-8 min" }, { title: "Strategie de scalabilite", desc: "Horizontal, vertical, cache, CDN", time: "8-10 min" }, { title: "Tests et monitoring", desc: "Definir les tests de charge et alertes", time: "5-8 min" } ] },
    { id: 16, firstName: "Jade", lastName: "Carpentier", agentName: "VP of Growth / Head of GTM", document: "Go-To-Market Plan", phase: 3, color: "#ff9f0a", photo: "assets/images/Jade Carpentier.webp", gptLink: "https://chatgpt.com/g/g-699f113802908191b94d1ea6e58ee4f9-jade-carpentier", shortDesc: "Decrit la strategie de lancement et de mise sur le marche.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/Go-To-Market Plan", howToUse: "Lancez la conversation avec Jade. Elle est allergique au \"spray and pray\" : distribuer partout sans strategie. Elle insiste sur le \"who\" avant le \"what\".", whatFor: "Le GTM Plan definit qui sont vos clients, comment les atteindre, a quel prix, par quels canaux, et avec quel calendrier.", whyUse: "Jade pense en systemes : chaque canal, message et metrique est interconnecte. Experience chez Spotify, HubSpot, Slack, Notion et Amazon.", methodology: [ { title: "Produit et marche", desc: "Comprendre le contexte et le marche", time: "8-10 min" }, { title: "Public cible et segments", desc: "Identifier les clients prioritaires", time: "8-10 min" }, { title: "Proposition de valeur", desc: "Articuler la differentiation", time: "5-8 min" }, { title: "Strategie d'acquisition", desc: "Choisir les canaux et tactiques", time: "8-10 min" }, { title: "Pricing et modele", desc: "Definir le positionnement prix", time: "5-8 min" }, { title: "Calendrier et metriques", desc: "Planifier le lancement et mesurer", time: "5-8 min" } ] },
    { id: 17, firstName: "Hana", lastName: "Okada", agentName: "Chief Risk Officer", document: "Risk Management Document", phase: 3, color: "#ff9f0a", photo: "assets/images/Hana Okada.webp", gptLink: "https://chatgpt.com/g/g-699f128799bc8191a6ad2d51914dab51-hana-okada", shortDesc: "Identifie les risques majeurs et les strategies pour les reduire.", folder: "Agents/ÉTAPE 3 — Croissance - Complexité/Risk Management Document", howToUse: "Lancez la conversation avec Hana. Elle explore en 5 phases : contexte, identification systematique des risques, evaluation, strategies de traitement, et suivi.", whatFor: "Le Risk Management Document transforme l'incertitude en information actionnable. Il cree une culture de gestion proactive des risques.", whyUse: "Hana est le \"pessimiste professionnel\" qui aide les optimistes a reussir. Elle pense en probabilites et impacts, jamais en certitudes. Experience chez Amazon, Google, McKinsey.", methodology: [ { title: "Contexte et enjeux", desc: "Comprendre le projet et ses enjeux", time: "5-8 min" }, { title: "Identifier les risques", desc: "Cartographier tous les risques", time: "10-15 min" }, { title: "Evaluer les risques", desc: "Probabilite x Impact pour chacun", time: "8-10 min" }, { title: "Strategies de traitement", desc: "Definir comment traiter chaque risque", time: "8-10 min" }, { title: "Structurer le suivi", desc: "Cadence de revue et responsables", time: "5 min" } ] },
    // === ETAPE 4 ===
    { id: 18, firstName: "Xavier", lastName: "Martin", agentName: "Expert Senior en Conformite", document: "Compliance Documentation", phase: 4, color: "#ff453a", photo: "assets/images/Xavier Martin.webp", gptLink: "https://chatgpt.com/g/g-699f144eda048191a70ad0230b1898cd-xavier-martin", shortDesc: "Garantit que le projet respecte les obligations legales et reglementaires.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Compliance Documentation", howToUse: "Lancez la conversation avec Xavier. Aucun angle mort reglementaire ne doit lui echapper. Il pense en \"compliance as code\".", whatFor: "La Compliance Documentation garantit que votre projet respecte TOUTES les obligations legales et reglementaires (RGPD, SOC2, ISO 27001...).", whyUse: "Xavier identifie les risques de non-conformite AVANT qu'ils ne deviennent des problemes. Plus de 15 ans d'experience en audit de conformite SaaS, fintech, healthtech.", methodology: [ { title: "Cadrage et contexte", desc: "Comprendre le secteur et les marches", time: "5-8 questions" }, { title: "Cartographie reglementaire", desc: "Identifier toutes les regulations", time: "6-8 questions" }, { title: "Audit de l'etat actuel", desc: "Evaluer la conformite existante", time: "8-10 questions" }, { title: "Plan de remediation", desc: "Prioriser les actions correctives", time: "5-7 questions" }, { title: "Validation et generation", desc: "Produire le document final", time: "Synthese" } ] },
    { id: 19, firstName: "William", lastName: "Chevalier", agentName: "Expert en Revue Juridique Tech", document: "Legal Review Document", phase: 4, color: "#ff453a", photo: "assets/images/William Chevalier.webp", gptLink: "https://chatgpt.com/g/g-699f15d613a08191a5012210f08c43c4-william-chevalier", shortDesc: "Analyse les implications juridiques liees au produit ou au service.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Legal Review Document", howToUse: "Lancez la conversation avec William. Il pose les questions inconfortables que personne ne veut entendre et quantifie l'impact de chaque risque juridique.", whatFor: "Le Legal Review Document analyse l'ensemble des implications juridiques : propriete intellectuelle, contrats, conformite, risques.", whyUse: "William cherche l'equilibre optimal entre protection et agilite business. Chaque zone grise juridique doit etre identifiee et traitee.", methodology: [ { title: "Cadrage et structure juridique", desc: "Comprendre l'entite et ses obligations", time: "5-7 questions" }, { title: "Propriete intellectuelle", desc: "Brevets, marques, code, donnees", time: "5-7 questions" }, { title: "Contrats et accords", desc: "Analyser tous les contrats", time: "5-7 questions" }, { title: "Risques et conformite", desc: "Identifier les risques juridiques", time: "5-7 questions" }, { title: "Synthese et recommandations", desc: "Prioriser les actions juridiques", time: "Synthese" } ] },
    { id: 20, firstName: "Nadia", lastName: "Benali", agentName: "Architecte Principal Senior", document: "Architecture Review Board Document", phase: 4, color: "#ff453a", photo: "assets/images/Nadia Benali.webp", gptLink: "https://chatgpt.com/g/g-699f16b91a6081919fb9da8de4b65622-nadia-benali", shortDesc: "Valide et supervise les choix d'architecture a grande echelle.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Architecture Review Board Document", howToUse: "Lancez la conversation avec Nadia. Elle utilise la methode ATAM. Elle ne valide JAMAIS sans avoir profondement questionne.", whatFor: "Le document ARB valide ou refuse une proposition architecturale majeure. Un mauvais choix peut couter des millions en refactoring.", whyUse: "Nadia est obsedee par les \"-ilities\" : scalability, reliability, maintainability. Plus de 20 ans d'experience chez Google, Amazon, Netflix et Spotify.", methodology: [ { title: "Contexte et drivers business", desc: "Comprendre les motivations du changement", time: "4-6 questions" }, { title: "Architecture actuelle", desc: "Analyser l'existant et ses limites", time: "4-6 questions" }, { title: "Architecture proposee", desc: "Examiner la solution en detail", time: "6-8 questions" }, { title: "Analyse d'impact et risques", desc: "Evaluer consequences et risques", time: "4-6 questions" }, { title: "Decision et plan de migration", desc: "Approuver/refuser + plan d'action", time: "4-6 questions" } ] },
    { id: 21, firstName: "Valerie", lastName: "Andre", agentName: "SRE Lead - Gestion d'Incidents", document: "Incident Report", phase: 4, color: "#ff453a", photo: "assets/images/Valerie Andre.webp", gptLink: "https://chatgpt.com/g/g-699f190d340081918a56ea6c1dd0a2cf-valerie-andre", shortDesc: "Documente les incidents majeurs et leurs impacts.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Incident Report", howToUse: "Lancez la conversation avec Valerie apres un incident. Chaque minute de la timeline doit etre exacte, chaque impact quantifie.", whatFor: "L'Incident Report documente un incident majeur : detection, timeline, impact, resolution et lecons apprises.", whyUse: "Valerie est calme et methodique sous pression. Elle defend la culture \"blameless\". Plus de 15 ans d'experience chez Google, Amazon, PagerDuty et Datadog.", methodology: [ { title: "Identification et cadrage", desc: "Classifier l'incident et sa severite", time: "4-5 questions" }, { title: "Reconstruction de la timeline", desc: "Minute par minute, que s'est-il passe ?", time: "6-8 questions" }, { title: "Analyse d'impact", desc: "Quantifier l'impact sur tous les plans", time: "4-6 questions" }, { title: "Cause racine et facteurs", desc: "Identifier la cause profonde", time: "5-7 questions" }, { title: "Actions correctives", desc: "Definir les actions pour prevenir", time: "3-5 questions" }, { title: "Validation et generation", desc: "Produire le rapport d'incident", time: "Synthese" } ] },
    { id: 22, firstName: "Cedric", lastName: "Petit", agentName: "Expert Post-Mortem", document: "Post-Mortem Document", phase: 4, color: "#ff453a", photo: "assets/images/Cedric Petit.webp", gptLink: "https://chatgpt.com/g/g-699f1a3be63c8191bb9f40505e351c89-cedric-petit", shortDesc: "Analyse les causes profondes d'un echec ou incident pour eviter qu'il se reproduise.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Post-Mortem Document", howToUse: "Lancez la conversation avec Cedric 24 a 72h APRES resolution. Contrairement a l'Incident Report, le post-mortem analyse le \"pourquoi\" en profondeur (methode des 5 Pourquoi).", whatFor: "Le Post-Mortem explore les causes systemiques, facteurs organisationnels, defaillances de processus et ameliorations structurelles.", whyUse: "Cedric refuse categoriquement tout blame individuel. Il pose \"pourquoi ?\" encore et encore jusqu'a la vraie cause racine. Inspire de Google, Etsy et Netflix.", methodology: [ { title: "Contexte et setup", desc: "Poser le cadre de l'analyse", time: "3-4 questions" }, { title: "Reconstruction detaillee", desc: "Reprendre les evenements en detail", time: "5-7 questions" }, { title: "Analyse des causes profondes", desc: "Methode des 5 Pourquoi", time: "6-8 questions" }, { title: "Apprentissages et resilience", desc: "Qu'avons-nous appris ?", time: "5-6 questions" }, { title: "Actions correctives", desc: "Comment prevenir a l'avenir ?", time: "4-5 questions" }, { title: "Validation et generation", desc: "Produire le post-mortem final", time: "Synthese" } ] },
    { id: 23, firstName: "Benjamin", lastName: "Caron", agentName: "Expert SRE - Niveaux de Service", document: "SLA Documentation", phase: 4, color: "#ff453a", photo: "assets/images/Benjamin Caron.webp", gptLink: "https://chatgpt.com/g/g-699f1bf3d6bc8191a9246042d84283e8-benjamin-caron", shortDesc: "Definit les engagements de performance et de disponibilite du service.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/SLA Documentation", howToUse: "Lancez la conversation avec Benjamin. Il refuse les SLA irrealistes : \"99.999% uptime\" sans monitoring, c'est non. Il pense en error budgets.", whatFor: "La SLA Documentation definit vos engagements formels : SLI (metrique) > SLO (objectif interne) > SLA (engagement contractuel).", whyUse: "Benjamin calibre des engagements honnetes et tenables, pas des promesses impossibles. Experience chez Google, Amazon AWS, Stripe et Datadog.", methodology: [ { title: "Comprehension du service", desc: "Comprendre le service et ses clients", time: "5-6 questions" }, { title: "Definition des SLI", desc: "Identifier les metriques cles", time: "5-7 questions" }, { title: "Calibrage des SLO", desc: "Fixer les objectifs internes realistes", time: "4-6 questions" }, { title: "Definition du SLA", desc: "Engagements contractuels et compensations", time: "5-7 questions" }, { title: "Validation et generation", desc: "Produire la documentation SLA", time: "Synthese" } ] },
    { id: 24, firstName: "Francois", lastName: "Roux", agentName: "Expert en Gouvernance Tech", document: "Governance Documentation", phase: 4, color: "#ff453a", photo: "assets/images/Francois Roux.webp", gptLink: "https://chatgpt.com/g/g-699f1cd7120881919b95b4d2039e4ee9-francois-roux", shortDesc: "Structure les regles internes de controle, validation et supervision du projet.", folder: "Agents/ÉTAPE 4 — Scale - Enterprise/Governance Documentation", howToUse: "Lancez la conversation avec Francois. \"On a toujours fait comme ca\" est sa phrase d'alerte maximale. Il refuse la bureaucratie inutile.", whatFor: "La Governance Documentation structure les regles de controle, validation et supervision. A 50 ou 200 personnes, sans gouvernance explicite, tout ralentit.", whyUse: "Francois concoit le minimum viable de gouvernance. Il pense en flux de decisions : chaque decision doit avoir un proprietaire clair. Plus de 20 ans d'experience.", methodology: [ { title: "Diagnostic organisationnel", desc: "Comprendre comment ca fonctionne aujourd'hui", time: "5-7 questions" }, { title: "Structure de decision", desc: "Qui decide quoi et comment", time: "5-7 questions" }, { title: "Processus operationnels", desc: "Comment le travail avance", time: "5-7 questions" }, { title: "Cadence et rituels", desc: "Definir les rythmes de l'organisation", time: "4-5 questions" }, { title: "Reporting et transparence", desc: "Comment l'information circule", time: "3-5 questions" }, { title: "Validation et generation", desc: "Produire le document de gouvernance", time: "Synthese" } ] }
];
